export const LOAD_HEAD_2_HEAD_STATS_REQUESTED = 'LOAD_HEAD_2_HEAD_STATS_REQUESTED';
export const LOAD_HEAD_2_HEAD_STATS_FAILED = 'LOAD_HEAD_2_HEAD_STATS_FAILED';
export const LOAD_HEAD_2_HEAD_STATS_SUCCESS = 'LOAD_HEAD_2_HEAD_STATS_SUCCESS';

export const SET_NEW_HEAD_2_HEAD = 'SET_NEW_HEAD_2_HEAD';
export const SET_FILTERED_MATCHES = 'SET_FILTERED_MATCHES';
