export const LOAD_HEAD_2_HEAD_STATS_REQUESTED = 'LOAD_HEAD_2_HEAD_STATS_REQUESTED';
export const LOAD_HEAD_2_HEAD_STATS_FAILED = 'LOAD_HEAD_2_HEAD_STATS_FAILED';

export const SET_PLAYED_MATCHES = 'SET_PLAYED_MATCHES';
export const SET_NEW_HEAD_2_HEAD = 'SET_NEW_HEAD_2_HEAD';
export const SET_FILTERED_MATCHES = 'SET_FILTERED_MATCHES';
export const CALCULATE_STATS = 'CALCULATE_STATS';
export const SET_FILTER_SURFACE = 'SET_FILTER_SURFACE';
export const SET_FILTER_YEAR = 'SET_FILTER_YEAR';
export const SET_FILTER_TOURNAMENT = 'SET_FILTER_TOURNAMENT';
export const INIT_DATA = 'INIT_DATA';
